language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
# Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
# Tagging
  - docker tag udagram-api-feed jmespartero/udagram-api-feed:v1
  - docker tag udagram-api-user jmespartero/udagram-api-user:v1
  - docker tag udagram-frontend jmespartero/udagram-frontend:v1
  - docker tag reverseproxy jmespartero/reverseproxy:v1
  
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jmespartero/udagram-api-feed:v1
  - docker push jmespartero/udagram-api-user:v1
  - docker push jmespartero/udagram-frontend:v1
  - docker push jmespartero/reverseproxy:v1
